version: "3"

vars:
  version: "0.3.1"
  license: "MIT"
  libname: "retrygo"
  coverfile: "coverage.out"
  
tasks:
  install-dev:
    desc: "Install development tools"
    cmds:
      - go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

  test:
    desc: "Run tests"
    vars:
      timeout: "5m"
    cmds:
      - go test -v -timeout {{.timeout}} -coverprofile={{.coverfile}} -covermode=atomic .
    
  bench:
    desc: "Run benchmarks only"
    vars:
      timeout: "5m"
    cmds:
      - go test -v -timeout {{.timeout}} -bench=. -run=^$$ -benchmem .

  show-cover:
    desc: "Show coverage"
    cmds:
      - go tool cover -html={{.coverfile}}
  
  doc:
    desc: "Generate documentation"
    vars:
      outputdir: "docs"
    cmds:
      - gomarkdoc -v -o '{{.outputdir}}/README.md' .

  release:
    desc: "Release a new version"
    cmds:
      - git tag v{{.version}}
      - git push origin v{{.version}}