name: Test Go

on:
  push:
    branches:
      - main

jobs:
  build-push-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2
    - name: Install go-task
      run: |
        curl -sL https://taskfile.dev/install.sh | sh
        sudo mv ./bin/task /usr/local/bin/task
    - name: Install dependencies
      run: task install-dev
    - name: 
      run: task doc
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update documentation"
        git push
